### ISSUE TITLE
Prod connectivity to SAF

### ISSUE THREAD

**Issue by chadbratton** [ca-cwds/devops#5]
Issue Description: County users cannot connect to Prod due to redirect issues within AWS.

Update **3/10/17**
The DevOps team is testing a resolution the morning of 3/10/17. An update will be posted with more details about the steps taken to resolve the issue.

**Comment by chadbratton** [comment]
@michaelsampath @vinod-taborda Michael or Vinod, please update this issue with the current status, thank you!

**Comment by michaelsampath** [comment]
Following steps were taken to resolve the issue.
1. Modify apache configuration file to redirect the root path to a subfolder as /intake/ as apache default route always point to the "/" when multiple proxy are given.
2. Add extra host within the docker container which redirects the domain name to a server IP address.

After making necessary changes, the application was tested with the integration with SAF and the problem was resolved.

**Comment by michaelsampath** [comment]
This issue has been resolved.
